name: Protect Core Files

on:
  pull_request:
    branches: [main]

jobs:
  check-core-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check for forbidden file modifications
      run: |
        git fetch origin main
        git diff --name-only origin/main HEAD > changed_files.txt
        if grep -qE '(LICENSE|ethics.core.json)' changed_files.txt; then
          echo "Unauthorized attempt to modify protected files."
          exit 1
        fi
